export { ReactComponent as PlayIconFill } from './icons/play_fill.svg'
export { ReactComponent as PlayIcon } from './icons/play.svg'
export { ReactComponent as StarIconFill } from './icons/star_fill.svg'
export { ReactComponent as StarIcon } from './icons/star.svg'
export { ReactComponent as HomeIcon } from './icons/home.svg'
export { ReactComponent as HomeIconFill } from './icons/home_fill.svg'
export { ReactComponent as AccountIcon } from './icons/account.svg'
export { ReactComponent as SearchIcon } from './icons/search.svg'
